### ISSUE TITLE
Scrolling on desktop browsers

### ISSUE THREAD

**Issue by Prinzhorn** [Famous/famous#277]
I basically ignored famo.us for the past months but today I jumped on it to evaluate it for a new project. Famo.us is advertised as a solution for mobile performance but still you're using it for scrolling on your (desktop) website (e.g. Famo.us University) and it's terrible (on desktop).

You probably already know that getting scrolling right on mobile is one of the hardest parts (see iScroll and others). But what you did is break desktop while trying to fix mobile. There are several open issues regarding scrolling and in some you say you need to add more keybindings to your implementation (page up/down, arrow keys etc.) and some are related to special devices which are not supported. Adding more complexity does not solve the issue. **There is nothing wrong with scrolling on desktop, so don't try to fix it**.

I propose a different "solution" to the scrolling problem, which can hopefully be applied the Famo.us for the ScrollView **on desktop** / non-touch devices: combine a wrapper element with `overflow:auto` with a child element which hosts all the content and uses `position:fixed` and a third spacer element which gives you the scroll height you need.

```html
<div class="scrollview">
    <div class="scrollview-spacer"></div>
    <div class="scrollview-content"></div>
</div>
```

```css
.scrollview {
    overflow:auto;

    width:123px;//handled by the layout manager
    height:123px;//handled by the layout manager
}

.scrollview-spacer {
    width:1px;
    position:absolute;
    top:0;
    pointer-events:none;
   
    height:12345px;//handled by the ScrollView class. Is set to the amount of scroll-height that is needed for the content.
}

//does not move when the parent is natively scrolled. the elements inside will be moved by Famo.us and the ScrollView
.scrollview-content {
    position:fixed;
    width:0;
    height:0;
    overflow:visible;
}
```

This gives you full native scrolling on desktop for every device and every keyboard shortcut and at the same time gives you full control over the positioning. Each time Famo.us does it's render loop, you simply grab the current native scroll position and move the contents accordingly.

Note: `position:fixed` does not work inside `transform`ed elements. But since Famo.us positions everything absolute and on the top level, it shouldn't be an issues to move the `scrollview` container to the root in order to position the content fixed.
